config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "pages#index"

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :savings_account_transactions, only: [:destroy]
  resources :insurance_account_transactions, only: [:destroy]

  resources :request_records, only: [:index, :show]

  # ADJUSTMENTS
  namespace :adjustments do
    resources :subsidiary_adjustments
    resources :transfer_adjustments
    resources :loan_payment_adjustments
    resources :batch_moratoria

    namespace :deposits do
      resources :payment_collections, except: [:new, :create]
    end

    namespace :withdrawals do
      resources :payment_collections, except: [:new, :create]
    end
    

    namespace :time_deposits do
      resources :operation_details do
        collection { get :list_of_time_deposit}
      end
    end


  end

  namespace :transfer do
    resources :center_transfer_records
  end

  ##################
  # MOUNTED ROUTES #
  ##################

  # Static pages
  draw :static
  draw :static_reports

  # API RELATED ROUTES
  draw :api
  draw :api_v2

  ###################

  resources :members do
    collection { post :import }
    collection { post :import_dependents }
    collection { post :import_beneficiaries }
    collection { post :import_correct_mii_recognition_date}
    collection { post :import_members_spouse_as_dependents}
    get "/resignation", to: "members#resignation"
    get "/transfer", to: "members#transfer"
    get "/resignation/edit", to: "members#edit_resignation"
    post "/resignation/:member_resignation_id/update", to: "members#update_resignation", as: :resignation_update
  end

  get "/download_transferred", to: "member_transfer_requests#download_transferred", as: :download_transferred

  # TRANSFER REQUESTS
  resources :member_transfer_requests, only: [:index, :edit, :show, :update]

  namespace :insurance  do
    resources :payment_collections do
      collection { post :upload }
    end
  end

  namespace :income_insurance  do
    resources :payment_collections do
      collection { post :upload }
    end
  end

  resources :feedbacks
  resources :surveys, only: [:index, :show] do
    resources :survey_respondents, except: [:index]
  end

  post "/new_loan_application", to: "loans#new_loan_application", as: :new_loan_application
  post "/new_claim_application", to: "claims#new_claim_application", as: :new_claim_application
  post "/new_clip_claim_application", to: "clip_claims#new_clip_claim_application", as: :new_clip_claim_application

  resources :branches
  resources :centers

  namespace :system_management do
    resources :users
    resources :centers
  end

  namespace :account do
    resources :users
  end

  namespace :accounting do
    get "/dashboard", to: "pages#dashboard"
    resources :loan_payments, only: [:index]
    resources :balance_sheets, only: [:index, :show, :destroy]
    resources :interest_on_share_capital_collections
    resources :patronage_refunds
    get "/patronage_refund/patronage_refund_excel", to: "patronage_refunds#patronage_refund_excel"
    get "/interest_on_share_capital_collection/interest_on_share_capital_excel", to: "interest_on_share_capital_collections#interest_on_share_capital_excel"
    get "/interest_on_share_capital_collection/interest_on_share_capital_pdf", to: "interest_on_share_capital_collections#interest_on_share_capital_pdf", as: :interest_on_share_capital_pdf

    get "/patronage_refund/patronage_refund_collection_pdf", to: "patronage_refunds#patronage_refund_collection_pdf", as: :patronage_refund_collection_pdf
    #get "/interest_on_share_capital_collections/index", to: "interest_on_share_capital_collections#index", as: :interest_on_share_capital_collections
    #get "/patronage_refunds", to: "patronage_refunds#patronage_refund_excel"

    get "/chart_of_accounts", to: "pages#chart_of_accounts", as: :chart_of_accounts
    get "/chart_of_accounts/download", to: "chart_of_accounts#download"
    get "/year_end_closing", to: "pages#year_end_closing"
    get "/income_statement", to: "pages#income_statement"
    get "/balance_sheet", to: "pages#balance_sheet"
    get "/reports/trial_balance", to: "reports#trial_balance", as: :reports_trial_balance
    get "/reports/financial_position", to: "reports#financial_position", as: :reports_financial_position
    get "/reports/statement_of_comprehensive_inc", to: "reports#statement_of_comprehensive_inc", as: :reports_statement_of_comprehensive_inc
  end

  get '/savings_accounts/monthly_interest_tax_generation', to: 'savings_accounts#manual_interest_tax_generation', as: :savings_accounts_manual_interest_tax_generation

  resources :claims do
    get "/claim_validation_pdf", to: "claims#claim_validation_pdf"
    get "/claim_loa_pdf", to: "claims#claim_loa_pdf"
  end

  resources :clip_claims do
    get "/clip_claim_validation_pdf", to: "clip_claims#clip_claim_validation_pdf"
    get "/clip_claim_loa_pdf", to: "clip_claims#clip_claim_loa_pdf"
  end

  resources :loans do
    get "/loan_ledger_pdf", to: "loans#loan_ledger_pdf"
    resources :loan_payments do
      get "approve_payment", to: "loan_payments#approve_payment", as: :approve
      get "reverse_payment", to: "loan_payments#reverse_payment", as: :reverse
    end
    resources :negative_loan_payments, except: [:index, :show]
    get "approve", to: "loans#approve", as: :approve
    get "reverse", to: "loans#reverse", as: :reverse
    get "writeoff", to: "loans#writeoff", as: :writeoff
    get "print_amortization", to: "loans#print_amortization", as: :print_amortization
  end

  resources :loan_insurances do
    collection { post :upload }
    get "approve", to: "loan_insurances#approve", as: :approve
    get "reverse", to: "loan_insurances#reverse", as: :reverse
  end

  resources :reinstatements do
    get "approve", to: "reinstatements#approve", as: :approve
    get "reverse", to: "reinstatements#reverse", as: :reverse
  end

  resources :insurance_account_validations do
    get "approve", to: "insurance_account_validations#approve", as: :approve
    get "reverse", to: "insurance_account_validations#reverse", as: :reverse

    get "/:insurance_account_validation_record_id/withdrawal_pdf", to: "insurance_account_validations#withdrawal_pdf", as: :withdrawal_pdf
    get "/pdf", to: "insurance_account_validations#pdf", as: :pdf
  end

  resources :deceased_and_total_and_permanent_disabilities do
    get "approve", to: "deceased_and_total_and_permanent_disabilities#approve", as: :approve
    get "reverse", to: "deceased_and_total_and_permanent_disabilities#reverse", as: :reverse
  end

  resources :payment_collections do
    get "/download_excel", to: "payment_collections#download_excel", as: :download_excel
    get "/download_wp_list", to: "payment_collections#download_wp_list", as: :download_wp_list
  end

  namespace :membership_payments do
    resources :payment_collections, only: [:index, :new, :show, :destroy, :edit, :update] do
      get "/pdf", to: "payment_collections#pdf"
      resources :payment_collection_records
    end
  end


  namespace :insurance do
    resources :payment_collections do
      get "/pdf", to: "payment_collections#pdf"
    end
  end

  # Member Accounts
  resources :savings_accounts
  resources :insurance_accounts do
    get "/claims_copy_pdf", to: "insurance_accounts#claims_copy_pdf"
    collection { post :import_insurance_accounts }
    collection { post :import_insurance_account_transactions }
    collection { post :import_insured_loans }
  end

  resources :equity_accounts

  # ACCOUNTING ROUTES
  resources :vouchers do
    get "approve", to: "vouchers#approve", as: :approve
    get "/pdf", to: "vouchers#pdf"
    get "/check_pdf", to: "vouchers#check_pdf"
  end

  resources :members do
    get "/change_beneficiaries_pdf", to: "members#change_beneficiaries_pdf"
    get "/blip_form_pdf", to: "members#blip_form_pdf"
    resources :loans, controller: 'members/loans', except: [:destroy] do
      get "/print_check", to: "members/loans#print_check"
      get "/print_voucher", to: "members/loans#print_voucher"
    end
    get "/transactions", to: "members#transactions", as: :transactions
    get "/toggle_active", to: "members#toggle_active", as: :toggle_active

    resources :member_shares, except: [:index] do
      get "/excel", to: "member_shares#excel"
      get "/pdf", to: "member_shares#pdf"
    end

    resources :member_certificates, except: [:index] do
      get "/excel", to: "member_certificates#excel"
      get "/pdf", to: "member_certificates#pdf"
      get "/certificates_for_printing", to: "member_certificates#certificates_for_printing"
    end

    resources :claims, controller: 'members/claims'
    resources :clip_claims, controller: 'members/clip_claims'
  end

  namespace :monitoring do
    resources :daily_reports, only: [:index, :show]
    resources :daily_report_insurance_account_statuses do
      get "/download_excel", to: "daily_report_insurance_account_statuses#download_excel"
    end
  end
  
  namespace :cash_management do
    namespace :time_deposits do
      resources :operation_details do
        collection { get :list_of_time_deposit}
      end
    end
    namespace :operations do
      resources :monthly_interest_and_tax_closing_records, only: [:index, :show, :destroy]
    end

    namespace :insurance_withdrawals do
      resources :payment_collections do
        get "/pdf", to: "payment_collections#pdf"
        collection { post :upload }
      end
    end

    namespace :equity_withdrawals do
      resources :payment_collections do
        get "/pdf", to: "payment_collections#pdf"
        collection { post :upload }
      end
    end

    namespace :deposits do

app/models/center_transfer_record.rb
class CenterTransferRecord < ApplicationRecord
  STATUSES = ["pending", "approved"]

  belongs_to :branch
  belongs_to :center

  has_many :center_transfer_record_journal_entries, dependent: :delete_all
  accepts_nested_attributes_for :center_transfer_record_journal_entries

  validates :uuid, presence: true, uniqueness: true
  validates :branch, presence: true
  validates :center, presence: true
  validates :data, presence: true
  validates :status, presence: true, inclusion: { in: STATUSES }
  validates :prepared_by, presence: true
  validates :approved_by, presence: true, if: :approved?
  validates :reference_number, presence: true, if: :approved?
  validates :particular, presence: true

	has_attached_file :file
  validates_attachment_content_type :file, content_type: ["text/plain"]
  validates :file, presence: true

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.uuid = SecureRandom.uuid
      self.status = "pending" if self.status.blank?
    end
  end

  def pending?
    self.status == "pending"
  end

  def approved?
    self.status == "approved"
  end

  def approve!
    self.update!(status: 'approved')
  end
end

app/controllers/api/v1/transfer/center_transfer_records_controller.rb
module Api
  module V1
    module Transfer
      class CenterTransferRecordsController < ApplicationController
        def approve
          center_transfer_record  = CenterTransferRecord.find(params[:id])
          user                    = current_user

          # TODO: Validate
          ::Transfer::ApproveCenterTransferRecord.new(
            center_transfer_record: center_transfer_record,
            user: user
          ).execute!

          render json: { message: "ok" }
        end
      end
    end
  end
end

app/controllers/transfer/center_transfer_records_controller.rb
module Transfer
  class CenterTransferRecordsController < ApplicationController
    before_action :authenticate_user!
    before_action :load_object, only: [:edit, :update, :show, :destroy]

    def load_object
      @center_transfer_record = CenterTransferRecord.find(params[:id])
    end

    def index
      @center_transfer_records  = CenterTransferRecord.select("*")
    end

    def new
      @center_transfer_record = CenterTransferRecord.new
    end

    def create
      @center_transfer_record = CenterTransferRecord.new(center_transfer_record_params)

      data  = Paperclip.io_adapters.for(@center_transfer_record.file).read
      @center_transfer_record.branch      = @center_transfer_record.center.try(:branch)
      @center_transfer_record.data        = data
      @center_transfer_record.prepared_by = current_user.full_name

      if @center_transfer_record.save
        flash[:success] = "Successfully created record"
        redirect_to transfer_center_transfer_record_path(@center_transfer_record)
      else
        Rails.logger.error @center_transfer_record.errors.messages
        flash[:error] = "Error in saving center transfer record"
        render :new
      end
    end

    def edit
    end

    def update
      data  = Paperclip.io_adapters.for(@center_transfer_record.file).read
      @center_transfer_record.branch      = @center_transfer_record.center.try(:branch)
      @center_transfer_record.data        = data
      @center_transfer_record.prepared_by = current_user.full_name

      if @center_transfer_record.update(center_transfer_record_params)
        flash[:success] = "Successfully updated record"
        redirect_to transfer_center_transfer_record_path(@center_transfer_record)
      else
        flash[:error] = "Error in saving center transfer record"
        render :edit
      end
    end

    def show
      @voucher  = ::Transfer::ProduceCenterTransferRecordAccountingEntry.new(
                    center_transfer_record: @center_transfer_record,
                    user: current_user
                  ).execute!
    end

    def destroy
      if @center_transfer_record.pending?
        @center_transfer_record.destroy!
        flash[:success] = "Successfully destroyed record"
        redirect_to transfer_center_transfer_records_path
      else
        flash[:error] = "Error in destroying center transfer record"
        redirect_to transfer_center_transfer_record_path(@center_transfer_record)
      end
    end

    private

    def center_transfer_record_params
      params.require(:center_transfer_record).permit!
    end
  end
end

app/views/transfer/center_transfer_records/_actions.html.haml
.well
  - if @center_transfer_record.pending?
    = link_to edit_transfer_center_transfer_record_path(@center_transfer_record), class: "btn btn-app" do
      .fa.fa-pencil
      Edit
    = link_to transfer_center_transfer_record_path(@center_transfer_record), class: "btn btn-app bg-red", method: :delete, data: { confirm: "Are you sure?" } do
      .fa.fa-times
      Delete
    = link_to "#", class: "btn btn-app bg-green", id: "btn-approve" do
      .fa.fa-check
      Approve

app/views/transfer/center_transfer_records/_center_transfer_record_journal_entry_fields.html.haml
.nested-fields
  .row
    .col-md-3
      = f.association :accounting_code, input_html: { class: "form-control select-select2" }
    .col-md-3
      = f.input :post_type, as: :select, collection: JournalEntry::POST_TYPES, input_html: { class: "form-control" }
    .col-md-3
      = f.input :amount, input_html: { class: "form-control" }
    .col-md-3
      %label
        Actions
      %br
      = link_to_remove_association f, class: "btn btn-danger" do
        .fa.fa-times
        Remove

app/views/transfer/center_transfer_records/_form.html.haml
= simple_form_for [:transfer, center_transfer_record] do |f|
  .row
    .col-md-6
      = f.association :center, input_html: { class: "form-control select-select2" }
    .col-md-6
      = f.input :file, as: :file
  %hr
  .row
    .col-md-12
      %h4
        Entries
      #center_transfer_record_journal_entries
        = f.simple_fields_for :center_transfer_record_journal_entries do |ff|
          = render 'center_transfer_record_journal_entry_fields', f: ff
        .links
          %hr
          = link_to_add_association f, :center_transfer_record_journal_entries, class: "btn btn-info" do
            .fa.fa-plus
            Add Entry
        %hr
  .row
    .col-md-12
      = f.input :particular, input_html: { class: "form-control" }
  .row
    .col-md-12
      .form-actions
        = button_tag type: "submit", class: "btn btn-primary" do
          .fa.fa-check
          Save Record
        - if center_transfer_record.new_record?
          = link_to transfer_center_transfer_records_path, class: "btn btn-default" do
            .fa.fa-times
            Cancel
        - else
          = link_to transfer_center_transfer_record_path(center_transfer_record), class: "btn btn-default" do
            .fa.fa-times
            Cancel

app/views/transfer/center_transfer_records/_list.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th From Branch
      %th Status
      %th Actions
  %tbody
    - @center_transfer_records.each do |center_transfer_record|
      %tr
        %td #{center_transfer_record.data['branch']}
        %td #{center_transfer_record.status}
        %td
          = link_to transfer_center_transfer_record_path(center_transfer_record) do
            .fa.fa-search
            Details

app/views/transfer/center_transfer_records/_member_beneficiaries.html.haml
%table.table.table-bordered
  %thead
    %th{width: "60%"}
      Name
    %th{width: "10%"}
      Date of Birth
    %th{width: "10%"}
      Age
    %th{width: "20%"}
      Relationship
  %tbody
    - beneficiaries.each do |beneficiary|
      %tr
        %td 
          #{beneficiary['last_name']}, #{beneficiary['first_name']} #{beneficiary['middle_name']}
        %td
          #{beneficiary['date_of_birth']}
        %td
          #{age(beneficiary['date_of_birth'].to_date)}
        %td
          #{beneficiary['relationship']}

app/views/transfer/center_transfer_records/_member_equity.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th{width: "20%"} Equity Type
      %th.acc-curr{width: "70%"} Balance
  %tbody
    - member_data['equity'].each do |equity_data|
      %tr
        %td #{EquityType.find(equity_data['equity_type_id'])}
        %td.curr #{number_to_currency(equity_data['balance'], unit: "")}

app/views/transfer/center_transfer_records/_member_insurance.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th{width: "20%"} Insurance Type
      %th.acc-curr{width: "70%"} Balance
  %tbody
    - member_data['insurance'].each do |insurance_data|
      %tr
        %td #{InsuranceType.find(insurance_data['insurance_type_id'])}
        %td.curr #{number_to_currency(insurance_data['balance'], unit: "")}

app/views/transfer/center_transfer_records/_member_legal_dependents.html.haml
%table.table.table-bordered
  %thead
    %th{width: "60%"}
      Name
    %th{width: "10%"}
      Date of Birth
    %th{width: "10%"}
      Age
    %th{width: "20%"}
      Educational Attainment
  %tbody
    - legal_dependents.each do |legal_dependent|
      %tr
        %td 
          #{legal_dependent['last_name']}, #{legal_dependent['first_name']} #{legal_dependent['middle_name']}
        %td
          #{legal_dependent['date_of_birth']}
        %td
          #{age(legal_dependent['date_of_birth'].to_date)}
        %td
          #{legal_dependent['educational_attainment']}

app/views/transfer/center_transfer_records/_member_loans.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th{width: "20%"} Loan Product
      %th.acc-curr{width: "20%"} Principal Balance
      %th.acc-curr{width: "20%"} Interest Balance
      %th{width: "20%"} Interest Rate
      %th{width: "20%"} Num Installments
  %tbody
    - member_data['loans'].each do |loan_data|
      %tr
        %td #{LoanProduct.find(loan_data['loan_product_id'])}
        %td.curr #{number_to_currency(loan_data['principal_balance'].to_f, unit: "")}
        %td.curr #{number_to_currency(loan_data['interest_balance'].to_f, unit: "")}
        %td #{loan_data['interest_rate']} %
        %td #{loan_data['num_installments']}

app/views/transfer/center_transfer_records/_member_savings.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th{width: "20%"} Savings Type
      %th.acc-curr{width: "70%"} Balance
  %tbody
    - member_data['savings'].each do |savings_data|
      %tr
        %td #{SavingsType.find(savings_data['savings_type_id'])}
        %td.curr #{number_to_currency(savings_data['balance'], unit: "")}

app/views/transfer/center_transfer_records/_totals.html.haml
%h4 Total for Loans

%table.table.table-bordered
  %thead
    %tr
      %th Loan Product
      %th.acc-curr Principal
      %th.acc-curr Interest
  %tbody
    - @center_transfer_record.data['totals']['loan_products'].each do |loan_data|
      %tr
        %td #{loan_data['loan_product']}
        %td.curr #{number_to_currency(loan_data['total_principal_balance'], unit: "")}
        %td.curr #{number_to_currency(loan_data['total_interest_balance'], unit: "")}

%h4 Total for Savings

%table.table.table-bordered
  %thead
    %tr
      %th Savings Type
      %th.acc-curr Balance
  %tbody
    - @center_transfer_record.data['totals']['savings'].each do |savings_data|
      %tr
        %td #{savings_data['savings_type']}
        %td.curr #{savings_data['total_amount']}

%h4 Total for Insurance

%table.table.table-bordered
  %thead
    %tr
      %th Insurance Type
      %th.acc-curr Balance
  %tbody
    - @center_transfer_record.data['totals']['insurance'].each do |insurance_data|
      %tr
        %td #{insurance_data['insurance_type']}
        %td.curr #{insurance_data['total_amount']}

%h4 Total for Equity

%table.table.table-bordered
  %thead
    %tr
      %th Equity Type
      %th.acc-curr Balance
  %tbody
    - @center_transfer_record.data['totals']['equity'].each do |equity_data|
      %tr
        %td #{equity_data['equity_type']}
        %td.curr #{equity_data['total_amount']}

app/views/transfer/center_transfer_records/edit.html.haml
%section.content-header
  %h1
    Edit Center Transfer Record

%section.content
  .box
    .box-body
      = render partial: "form", locals: { center_transfer_record: @center_transfer_record }

app/views/transfer/center_transfer_records/index.html.haml
%section.content-header
  %h1
    Center Transfer Record
  %ol.breadcrumb
    %li{:style => "margin-top: -10px;"}
      = link_to new_transfer_center_transfer_record_path, id: 'new-record', style: "color: #fff;", class: 'btn btn-primary bg-blue normal' do
        .fa.fa-plus
        Generate New Center Transfer Record

%section.content
  .box
    .box-body
      - if @center_transfer_records.size > 0
        = render partial: "list"
      - else
        No records found

app/views/transfer/center_transfer_records/new.html.haml
%section.content-header
  %h1
    New Center Transfer Record

%section.content
  .box
    .box-body
      = render partial: "form", locals: { center_transfer_record: @center_transfer_record }