config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "pages#index"

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :savings_account_transactions, only: [:destroy]
  resources :insurance_account_transactions, only: [:destroy]

  resources :request_records, only: [:index, :show]

  # ADJUSTMENTS
  namespace :adjustments do
    resources :subsidiary_adjustments
    resources :transfer_adjustments
    resources :loan_payment_adjustments
    resources :batch_moratoria

    namespace :deposits do
      resources :payment_collections, except: [:new, :create]
    end

    namespace :withdrawals do
      resources :payment_collections, except: [:new, :create]
    end
    

    namespace :time_deposits do
      resources :operation_details do
        collection { get :list_of_time_deposit}
      end
    end


  end

  namespace :transfer do
    resources :center_transfer_records
  end

  ##################
  # MOUNTED ROUTES #
  ##################

  # Static pages
  draw :static
  draw :static_reports

  # API RELATED ROUTES
  draw :api
  draw :api_v2

  ###################

  resources :members do
    collection { post :import }
    collection { post :import_dependents }
    collection { post :import_beneficiaries }
    collection { post :import_correct_mii_recognition_date}
    collection { post :import_members_spouse_as_dependents}
    get "/resignation", to: "members#resignation"
    get "/transfer", to: "members#transfer"
    get "/resignation/edit", to: "members#edit_resignation"
    post "/resignation/:member_resignation_id/update", to: "members#update_resignation", as: :resignation_update
  end

  get "/download_transferred", to: "member_transfer_requests#download_transferred", as: :download_transferred

  # TRANSFER REQUESTS
  resources :member_transfer_requests, only: [:index, :edit, :show, :update]

  namespace :insurance  do
    resources :payment_collections do
      collection { post :upload }
    end
  end

  namespace :income_insurance  do
    resources :payment_collections do
      collection { post :upload }
    end
  end

  resources :feedbacks
  resources :surveys, only: [:index, :show] do
    resources :survey_respondents, except: [:index]
  end

  post "/new_loan_application", to: "loans#new_loan_application", as: :new_loan_application
  post "/new_claim_application", to: "claims#new_claim_application", as: :new_claim_application
  post "/new_clip_claim_application", to: "clip_claims#new_clip_claim_application", as: :new_clip_claim_application

  resources :branches
  resources :centers

  namespace :system_management do
    resources :users
    resources :centers
  end

  namespace :account do
    resources :users
  end

  namespace :accounting do
    get "/dashboard", to: "pages#dashboard"
    resources :loan_payments, only: [:index]
    resources :balance_sheets, only: [:index, :show, :destroy]
    resources :interest_on_share_capital_collections
    resources :patronage_refunds
    get "/patronage_refund/patronage_refund_excel", to: "patronage_refunds#patronage_refund_excel"
    get "/interest_on_share_capital_collection/interest_on_share_capital_excel", to: "interest_on_share_capital_collections#interest_on_share_capital_excel"
    get "/interest_on_share_capital_collection/interest_on_share_capital_pdf", to: "interest_on_share_capital_collections#interest_on_share_capital_pdf", as: :interest_on_share_capital_pdf

    get "/patronage_refund/patronage_refund_collection_pdf", to: "patronage_refunds#patronage_refund_collection_pdf", as: :patronage_refund_collection_pdf
    #get "/interest_on_share_capital_collections/index", to: "interest_on_share_capital_collections#index", as: :interest_on_share_capital_collections
    #get "/patronage_refunds", to: "patronage_refunds#patronage_refund_excel"

    get "/chart_of_accounts", to: "pages#chart_of_accounts", as: :chart_of_accounts
    get "/chart_of_accounts/download", to: "chart_of_accounts#download"
    get "/year_end_closing", to: "pages#year_end_closing"
    get "/income_statement", to: "pages#income_statement"
    get "/balance_sheet", to: "pages#balance_sheet"
    get "/reports/trial_balance", to: "reports#trial_balance", as: :reports_trial_balance
    get "/reports/financial_position", to: "reports#financial_position", as: :reports_financial_position
    get "/reports/statement_of_comprehensive_inc", to: "reports#statement_of_comprehensive_inc", as: :reports_statement_of_comprehensive_inc
  end

  get '/savings_accounts/monthly_interest_tax_generation', to: 'savings_accounts#manual_interest_tax_generation', as: :savings_accounts_manual_interest_tax_generation

  resources :claims do
    get "/claim_validation_pdf", to: "claims#claim_validation_pdf"
    get "/claim_loa_pdf", to: "claims#claim_loa_pdf"
  end

  resources :clip_claims do
    get "/clip_claim_validation_pdf", to: "clip_claims#clip_claim_validation_pdf"
    get "/clip_claim_loa_pdf", to: "clip_claims#clip_claim_loa_pdf"
  end

  resources :loans do
    get "/loan_ledger_pdf", to: "loans#loan_ledger_pdf"
    resources :loan_payments do
      get "approve_payment", to: "loan_payments#approve_payment", as: :approve
      get "reverse_payment", to: "loan_payments#reverse_payment", as: :reverse
    end
    resources :negative_loan_payments, except: [:index, :show]
    get "approve", to: "loans#approve", as: :approve
    get "reverse", to: "loans#reverse", as: :reverse
    get "writeoff", to: "loans#writeoff", as: :writeoff
    get "print_amortization", to: "loans#print_amortization", as: :print_amortization
  end

  resources :loan_insurances do
    collection { post :upload }
    get "approve", to: "loan_insurances#approve", as: :approve
    get "reverse", to: "loan_insurances#reverse", as: :reverse
  end

  resources :reinstatements do
    get "approve", to: "reinstatements#approve", as: :approve
    get "reverse", to: "reinstatements#reverse", as: :reverse
  end

  resources :insurance_account_validations do
    get "approve", to: "insurance_account_validations#approve", as: :approve
    get "reverse", to: "insurance_account_validations#reverse", as: :reverse

    get "/:insurance_account_validation_record_id/withdrawal_pdf", to: "insurance_account_validations#withdrawal_pdf", as: :withdrawal_pdf
    get "/pdf", to: "insurance_account_validations#pdf", as: :pdf
  end

  resources :deceased_and_total_and_permanent_disabilities do
    get "approve", to: "deceased_and_total_and_permanent_disabilities#approve", as: :approve
    get "reverse", to: "deceased_and_total_and_permanent_disabilities#reverse", as: :reverse
  end

  resources :payment_collections do
    get "/download_excel", to: "payment_collections#download_excel", as: :download_excel
    get "/download_wp_list", to: "payment_collections#download_wp_list", as: :download_wp_list
  end

  namespace :membership_payments do
    resources :payment_collections, only: [:index, :new, :show, :destroy, :edit, :update] do
      get "/pdf", to: "payment_collections#pdf"
      resources :payment_collection_records
    end
  end


  namespace :insurance do
    resources :payment_collections do
      get "/pdf", to: "payment_collections#pdf"
    end
  end

  # Member Accounts
  resources :savings_accounts
  resources :insurance_accounts do
    get "/claims_copy_pdf", to: "insurance_accounts#claims_copy_pdf"
    collection { post :import_insurance_accounts }
    collection { post :import_insurance_account_transactions }
    collection { post :import_insured_loans }
  end

  resources :equity_accounts

  # ACCOUNTING ROUTES
  resources :vouchers do
    get "approve", to: "vouchers#approve", as: :approve
    get "/pdf", to: "vouchers#pdf"
    get "/check_pdf", to: "vouchers#check_pdf"
  end

  resources :members do
    get "/change_beneficiaries_pdf", to: "members#change_beneficiaries_pdf"
    get "/blip_form_pdf", to: "members#blip_form_pdf"
    resources :loans, controller: 'members/loans', except: [:destroy] do
      get "/print_check", to: "members/loans#print_check"
      get "/print_voucher", to: "members/loans#print_voucher"
    end
    get "/transactions", to: "members#transactions", as: :transactions
    get "/toggle_active", to: "members#toggle_active", as: :toggle_active

    resources :member_shares, except: [:index] do
      get "/excel", to: "member_shares#excel"
      get "/pdf", to: "member_shares#pdf"
    end

    resources :member_certificates, except: [:index] do
      get "/excel", to: "member_certificates#excel"
      get "/pdf", to: "member_certificates#pdf"
      get "/certificates_for_printing", to: "member_certificates#certificates_for_printing"
    end

    resources :claims, controller: 'members/claims'
    resources :clip_claims, controller: 'members/clip_claims'
  end

  namespace :monitoring do
    resources :daily_reports, only: [:index, :show]
    resources :daily_report_insurance_account_statuses do
      get "/download_excel", to: "daily_report_insurance_account_statuses#download_excel"
    end
  end
  
  namespace :cash_management do
    namespace :time_deposits do
      resources :operation_details do
        collection { get :list_of_time_deposit}
      end
    end
    namespace :operations do
      resources :monthly_interest_and_tax_closing_records, only: [:index, :show, :destroy]
    end

    namespace :insurance_withdrawals do
      resources :payment_collections do
        get "/pdf", to: "payment_collections#pdf"
        collection { post :upload }
      end
    end

    namespace :equity_withdrawals do
      resources :payment_collections do
        get "/pdf", to: "payment_collections#pdf"
        collection { post :upload }
      end
    end

    namespace :deposits do

app/models/member_share.rb
class MemberShare < ApplicationRecord
  STATUSES = ["pending", "approved"]

  validates :uuid, presence: true, uniqueness: true
  validates :certificate_number, presence: true, uniqueness: true
  validates :date_of_issue, presence: true
  validates :number_of_shares, presence: true, numericality: true
  validates :status, presence: true, inclusion: { in: STATUSES }

  belongs_to :member

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.uuid = "#{SecureRandom.uuid}" if self.uuid.nil?
      self.status = "pending"
      #self.number_of_shares = 1
      self.is_void != true
    end
  end

  def to_version_2_hash
    {
      id: self.uuid,
      member_id: self.member.uuid,
      certificate_number: self.certificate_number,
      date_of_issue: self.date_of_issue,
      number_of_shares: self.number_of_shares,
      data: {
        printed: self.printed,
        date_printed: self.date_printed
      }
    }
  end

  def to_transfer_hash
    {
      uuid: self.uuid,
      member_id: self.member.uuid,
      certificate_number: self.certificate_number,
      date_of_issue: self.date_of_issue,
      printed: self.printed,
      date_printed: self.date_printed,
      number_of_shares: self.number_of_shares
    }
  end


  def to_s
    certificate_number
  end
end

app/controllers/api/v1/member_shares_controller.rb
module Api
  module V1
    class MemberSharesController < ApplicationController
      def flag_for_printing
        member_share  = MemberShare.find(params[:id])
        member_share.update!(
          printed: true,
          date_printed: ApplicationHelper.current_working_date
        )

        render json: { member_share: member_share }
      end
    end
  end
end

app/controllers/member_shares_controller.rb
class MemberSharesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_member, except: [:index, :shares_for_printing,:shares_printed_pdf]

  def index
    #@member_shares  = MemberShare.joins(:member).order("member_shares.printed, members.last_name ASC, members.status ASC")
    @member_shares = MemberShare.joins(:member).order("member_shares.date_printed DESC, members.status, member_shares.date_of_issue ,members.last_name ASC")

    if params[:q].present?
      @q  = params[:q]

      @member_shares  = @member_shares.where("member_shares.certificate_number LIKE ?", "#{@q}%")
    end

    if params[:start_date_of_issue].present? and params[:end_date_of_issue].present?
      @start_date_of_issue = params[:start_date_of_issue]
      @end_date_of_issue   = params[:end_date_of_issue]


      @member_shares  = @member_shares.where("member_shares.date_of_issue >= ? AND member_shares.date_of_issue <= ?", @start_date_of_issue, @end_date_of_issue)
    end

    if params[:start_date_printed].present? and params[:end_date_printed].present?
      @start_date_printed = params[:start_date_printed]
      @end_date_printed   = params[:end_date_printed]

      @member_shares  = @member_shares.where("member_shares.date_printed >= ? AND member_shares.date_printed <= ?", @start_date_printed, @end_date_printed)
    end
    
    @limit = 100
    @counter = 0
    if params[:page].present?
      @counter = (params[:page].to_i - 1)  * @limit
    end
    @member_shares  = @member_shares.page(params[:page]).per(@limit)
  end


  def shares_printed_pdf
    @member_shared = MemberShare.joins(:member => :center).order("member_shares.date_of_issue ASC, members.status, member_shares.date_printed,members.last_name ASC")

    if params[:start_date_of_issue].present? and params[:end_date_of_issue].present?
      @start_date_of_issue = params[:start_date_of_issue]
      @end_date_of_issue   = params[:end_date_of_issue]

      @member_shared  = @member_shared.where("member_shares.date_of_issue >= ? AND member_shares.date_of_issue <= ?", @start_date_of_issue, @end_date_of_issue)
    end

    if params[:start_date_printed].present? and params[:end_date_printed].present?
      @start_date_printed = params[:start_date_printed]
      @end_date_printed   = params[:end_date_printed]

      @member_shared  = @member_shared.where("member_shares.date_printed >= ? AND member_shares.date_printed <= ?", @start_date_printed, @end_date_printed)
    end
  end

  def load_member
    @member = Member.find(params[:member_id])
    #if !@member.active?
    if !["active", "resigned", "resign"].include?(@member.status)
      flash[:error] = "Cannot issue share to non-active member"
      redirect_to member_path(@member)
    end
  end

  def shares_for_printing
    #printed_member_shares = MemberShare.where(printed: true , is_void: '')
    #printed_member_ids    = Member.where(id: printed_member_shares.pluck(:member_id))
    #@members_for_printing = Member.active.where.not(id: printed_member_ids).order("previous_mfi_member_since ASC, last_name ASC")
    @data = {}
    @data[:sfp] = []
    x = Member.joins(:equity_accounts).where("members.status = 'active'").order("equity_accounts.updated_at ASC")
  
    x.each do |y|
      sfp = {}
      eq = EquityAccount.where("member_id = ?" , y.id).sum(:balance).to_i
      eq_date = EquityAccount.where("member_id = ?" , y.id).pluck(:updated_at).to_s
      eqm = eq/100
      mem = Member.joins(:member_shares).where("members.id = ? and member_shares.is_void IS NULL" , y.id).sum(:number_of_shares)
      if eqm > mem
        sfp[:full_name] = y.full_name
        sfp[:id] = y.id
        sfp_center = y.center_id
        sfp[:center] = Center.find(sfp_center).name
        sfp[:shares_printed] = mem
        sfp[:shares_for_printing] = eqm - mem
        sfp[:update_date] = eq_date.to_date 
        @data[:sfp] << sfp
        
      end
    end
    @data
  end

  def pdf
    @member_share = MemberShare.find(params[:member_share_id])
  end

  def excel
    @member_share = MemberShare.find(params[:member_share_id])
    filename = "share_#{@member_share.certificate_number}.xlsx"
    report_package  = Members::GenerateMemberShareCertificateExcel.new(member: @member, member_share: @member_share).execute!
    report_package.serialize "#{Rails.root}/tmp/#{filename}"
    send_file "#{Rails.root}/tmp/#{filename}", filename: "#{filename}", type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  end

  def new
    @x = EquityAccountTransaction.joins(:equity_account).where("equity_accounts.member_id = ?", @member.id).last
    x_count = (@x.amount/100).to_i
    #@member_share = MemberShare.new(number_of_shares: 1 , date_of_issue: @member.date_accepted_coop)
    @member_share = MemberShare.new(number_of_shares: x_count , date_of_issue: @x.transacted_at)
  end

  def create
    @member_share = MemberShare.new(member_share_params)
    @member_share.member = @member

    if @member_share.save
      flash[:success] = "Successfully saved member share"
      redirect_to member_member_share_path(@member, @member_share)
    else
      flash[:error] = "Cannot save member share"
      render :new
    end
  end

  def edit
    @member_share = MemberShare.find(params[:id])
  end

  def update
    @member_share = MemberShare.find(params[:id])

    if @member_share.update(member_share_params)
      flash[:success] = "Successfully saved member share"
      redirect_to member_member_share_path(@member, @member_share)
    else
      flash[:error] = "Cannot save member share"
      render :edit
    end
  end

  def destroy
    @member_share = MemberShare.find(params[:id])
    @member_share.destroy!
    flash[:success] = "Successfully deleted member share"
    redirect_to member_path(@member)
  end

  def show
    @member_share = MemberShare.find(params[:id])
  end

  def member_share_params
    params.require(:member_share).permit!
  end
end

app/views/member_shares/_filter.html.haml
#filter
  = form_tag member_shares_path, html: { novalidate: true }, method: "GET", defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control simple_form' } } do
    %table.table.table-bordered.table-responsive
      %tr
        %th
          %label Cert Number
          = text_field_tag :q, @q, placeholder: "Cert Number", class: "form-control"
        %th
          %label Date of Issue
          .row
            .col-md-6
              = text_field_tag :start_date_of_issue, @start_date_of_issue, class: "datepick form-control", placeholder: "Start Date"
            .col-md-6
              = text_field_tag :end_date_of_issue, @end_date_of_issue, class: "datepick form-control", placeholder: "End Date"
        %th
          %label Date Printed
          .row
            .col-md-6
              = text_field_tag :start_date_printed, @start_date_printed, class: "datepick form-control", placeholder: "Start Date"
            .col-md-6
              = text_field_tag :end_date_printed, @end_date_printed, class: "datepick form-control", placeholder: "End Date"
        %th
          %label Actions
          %br
          = button_tag :submit, class: 'btn btn-primary' do
            .fa.fa-search
          &nbsp
          = link_to shares_printed_pdf_path start_date_of_issue: @start_date_of_issue , end_date_of_issue: @end_date_of_issue , start_date_printed: @start_date_printed , end_date_printed: @end_date_printed , target: "_blank" do
            .fa.fa-print
            Print to PDF

app/views/member_shares/_form.html.haml
= simple_form_for [@member, @member_share], defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control form-submit-loading' } }, html: { multipart: true, novalidate: true } do |f|
  = f.input :date_of_issue
  = f.input :certificate_number
  = f.input :number_of_shares
  .form-actions
    = button_tag :submit, :class => "btn btn-primary" do
      .fa.fa-check
      Save Record
    = link_to member_path(@member), class: "btn btn-default" do
      .fa.fa-times
      Cancel

app/views/member_shares/_list.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th
      %th Certificate No.
      %th Member
      %th Date of Issue
      %th Member Status
      %th Date Printed
      %th
  %tbody

  

    - member_shares.each_with_index do |member_share, index|
      - @counter = @counter + 1
      %tr.clickable{ data: { id: member_share.id, member_id: member_share.member.id } }
        %td
          #{@counter}
        %td
          #{member_share}
        %td
          = link_to member_path(member_share.member) do
            #{member_share.member.full_name_titleize}
        %td
          -if member_share.date_of_issue.present?
            #{member_share.date_of_issue.strftime("%m-%d-%Y")}
      
        %td
          #{member_share.member.status}
        %td
          -if member_share.date_printed.present?
            #{member_share.date_printed.strftime("%m-%d-%Y")}
        %td
          - if member_share.printed
            %label.label.label-success
              Printed
          - else
            %label.label.label-danger
              Not Printed

app/views/member_shares/edit.html.haml
%section.content-header
  %h1
    Member Shares Form
    %small Edit Share #{@member_share.certificate_number}
  %ol.breadcrumb
    %li
      = link_to member_path(@member), class: '' do
        .fa.fa-arrow-left
        #{@member.full_name}
%section.content
  = render partial: "form", locals: { member: @member, member_share: @member_share }

app/views/member_shares/index.html.haml
%section.content-header
  %h1
    Member Shares

%section.content
  = render partial: "filter"
  .box
    .box-body
      - if @member_shares.count > 0
        = render partial: "list", locals: { member_shares: @member_shares }
        = paginate @member_shares
      - else
        No records found

= javascript_include_tag "member_shares/Index"

:javascript
  $(document).ready(function() {
    Index.init();
  });

app/views/member_shares/new.html.haml
%section.content-header
  %h1
    Member Shares Form
    %small New Share
  %ol.breadcrumb
    %li
      = link_to member_path(@member), class: '' do
        .fa.fa-arrow-left
        #{@member.full_name}
%section.content
  = render partial: "form", locals: { member: @member, member_share: @member_share }

app/views/member_shares/pdf.html.haml
:css
  #certificate-details{

  }
  .member-details {
    margin: 61px 0px 0px 250px;
  }

  .member-no-of-share {
     margin: 33px 0px 0px 250px;
  }

  .member-name {
    margin-top: 265px;
    max-width: 900px;
  }

  .member-recognition-month {
    margin-left: 105px;
  }

  .member-recognition-year {
    margin-left: 150px;
  }
  
  .pangulo-sign{
    margin-left:110px;
    margin-right:300px;
  }

  .sign{
    margin-top:-5px;
  }

  .name{
    margin-top: -50px;
  }

  .kalihim-name{
    font-size: 12px;
    margin-left:100px;
    margin-right:270px;
  }

  .pangulo-name{
    font-size: 12px;
  }

  .kalihim-pos{
    font-size: 11px;
    margin-left:140px;
    margin-right:350px;
  }

  .pos{
    margin-top: -10px;
  }

  .pangulo-pos{
    font-size: 11px;
  }

#certificate-details
  .member-name
    %center
      %h1
        #{@member.to_s.upcase}
  .member-no-of-share
    - if @member_share.number_of_shares == 3
      %label
        tatlong ( #{@member_share.number_of_shares} )
    - if @member_share.number_of_shares == 2
      %label
        dalawang ( #{@member_share.number_of_shares} )
    - if @member_share.number_of_shares == 1
      %label
        isang ( #{@member_share.number_of_shares} )
  .member-details
    %label
      #{@member_share.date_of_issue.day.ordinalize}
    %label.member-recognition-month
      #{month_to_filipino(@member_share.date_of_issue.month).capitalize}
    %label{ class: "member-recognition-year" }
      #{@member_share.date_of_issue.year}
  - if Settings.share_signatories == true
    .sign
      %label.pangulo-sign
        = image_tag "signatures/kalihim.bmp", class: "img-responsive" , size: "120"
      %label
        = image_tag "signatures/taga_pangulo.bmp", class: "img-responsive" , size: "70"
    .name
      %label.kalihim-name
        #{Settings.kalihim}
      %label.pangulo-name
        #{Settings.taga_pangulo}
    .pos
      %label.kalihim-pos
        Kalihim
      %label.pangulo-pos
        Taga Pangulo
 

app/views/member_shares/shares_for_printing.html.haml
%section.content-header
  %h1
    Shares for Printing

%section.content
  .box
    .box-body
    -if @data != nil
      %table.table.table-bordered
        %thead
          %tr
            %th{ width: "5%" }
            %th Member
            %th Center
            %th Shares Printed
            %th Shares For Printing
            %th Last Payment - Equity
        %tbody
          - @data[:sfp].each_with_index do |sfp, i|
            %tr
              %td
                #{i + 1}
              %td
                = link_to member_path(sfp[:id]), target: '_blank' do
                  #{sfp[:full_name]}
              %td
                #{sfp[:center]}
              %td
                #{sfp[:shares_printed]}
              %td
                #{sfp[:shares_for_printing]}
              %th
                #{sfp[:update_date]}

app/views/member_shares/shares_printed_pdf.html.haml
%table{:style => "font-size:x-small; width: 95%"}
  %thead
    %tr
      %td{:colspan => 4}
        %table{:style => "font-wight: bold"}
          %tr
            %td
              #{Settings.company}
          %tr
            %td
              #{Settings.company_address}
          %tr
            %td
              VAT Registration Tin Number:#{Settings.tin_number}
          %tr
            %td
              SHARE CERTIFICATE SUMMARY
          %tr
            %td
              #{Branch.first.name}
          %tr
            %td 
              -if @start_date_printed != nil && @end_date_printed != nil
                Date Printed Period :  #{(@start_date_printed.to_date).strftime("%m/%d/%y")} - #{(@end_date_printed.to_date).strftime("%m/%d/%y")}

%table.table.table-bordered{:style => "border:1px black solid;font-size: x-small;margin-bottom: 2%;margin-top: 2%"}

  %thead
    %tr
      %th{:style => "width: 3%"}
      %th{:style => "width: 25%"} Name
      %th{:style => "width: 20%"} Center
      %th{:style => "width: 15%"} Certificate No.
      %th{:style => "width: 10%"} Date of Membership
      %th{:style => "width: 10%"} Date Printed
      %th{:style => "width: 15%"} RECIEVED BY:
  %tbody

  

    - @member_shared.each_with_index do |member_share, index|
      - @counter = index + 1
      %tr
        %td
          #{@counter}
        %td
          #{member_share.member.full_name_titleize}
        %td
          #{member_share.member.center.name}
        %td
          #{member_share}
        %td
          #{member_share.date_of_issue.strftime("%m-%d-%Y")}
        %td
          #{member_share.date_printed.strftime("%m-%d-%Y")}
        %td

%table{:style => "font-size: x-small;margin-bottom:2%;margin-top:3%;width:100%"}
  %tr
    %td{:style => "padding-left:1%;width:25%;height:40px"}Prepared By:
    %td{:align => 'center', :style => "padding-left: 1%; width: 25%;padding-top:5%"} 
    %td{:style => "padding-left:1%;width:25%;height:40px"} Checked By:
    %td{:align => 'center', :style => "padding-left: 1%; width: 25%;padding-top:5%"}
  %tr
    %td{:style => "padding-left:1%;width:25%;height:40px"}Operations Assistant
    %td{:align => 'center', :style => "padding-left: 1%; width: 25%;padding-top:5%"}
    
    %td{:style => "padding-left:1%;width:25%;height:40px"} Accounting Officer
    %td{:align => 'center', :style => "padding-left: 1%; width: 100%;padding-top:5%"}

app/views/member_shares/show.html.haml
%section.content-header
  %h1
    Member Share Record
    %small #{@member.full_name}
  %ol.breadcrumb
    %li
      = link_to member_path(@member), class: '' do
        .fa.fa-arrow-left
        #{@member.full_name}

%section.content
  .box
    .box-header
    .box-content
      = link_to member_member_share_excel_path(@member, @member_share), class: 'btn btn-app btn-default' do
        .fa.fa-download
        Download
      = link_to member_member_share_pdf_path(@member, @member_share), class: 'btn btn-app btn-default', target: '_blank' do
        .fa.fa-download 
        PDF
      = link_to edit_member_member_share_path(@member, @member_share), class: 'btn btn-app btn-default' do
        .fa.fa-pencil
        Edit
      = link_to member_path(@member), class: 'btn btn-app btn-default' do
        .fa.fa-arrow-left
        Back
      = link_to member_shares_path, class: 'btn btn-app btn-default' do
        .fa.fa-arrow-left
        Back to List

  %table.ui.green.table
    %tr
      %th{width: "20%"} Date of Issue
      %td #{@member_share.date_of_issue}
    %tr
      %th Certificate Number:
      %td #{@member_share.certificate_number}
    %tr
      %th Number of Shares:
      %td #{@member_share.number_of_shares}
    %tr
      %th Date Printed
      %td
        - if @member_share.printed
          #{@member_share.date_printed.strftime("%B %d, %Y")}
        - else
          = button_tag :flag_for_printing, id: 'btn-flag-for-printing', class: "btn btn-primary" do
            .fa.fa-printer
            Flag for Printing

  - if ["MIS", "BK", "SBK"].include? current_user.role
    .bs-callout.bs-callout-danger
      %h4
        Danger Zone
      = link_to member_member_share_path(@member, @member_share), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do
        .fa.fa-times
        Delete

#parameters{ data: { id: @member_share.id, member_id: @member.id } }
= javascript_include_tag "member_shares/Show"

:javascript
  $(document).ready(function() {
    Show.init();
  });