config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "pages#index"

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :savings_account_transactions, only: [:destroy]
  resources :insurance_account_transactions, only: [:destroy]

  resources :request_records, only: [:index, :show]

  # ADJUSTMENTS
  namespace :adjustments do
    resources :subsidiary_adjustments
    resources :transfer_adjustments
    resources :loan_payment_adjustments
    resources :batch_moratoria

    namespace :deposits do
      resources :payment_collections, except: [:new, :create]
    end

    namespace :withdrawals do
      resources :payment_collections, except: [:new, :create]
    end
    

    namespace :time_deposits do
      resources :operation_details do
        collection { get :list_of_time_deposit}
      end
    end


  end

  namespace :transfer do
    resources :center_transfer_records
  end

  ##################
  # MOUNTED ROUTES #
  ##################

  # Static pages
  draw :static
  draw :static_reports

  # API RELATED ROUTES
  draw :api
  draw :api_v2

  ###################

  resources :members do
    collection { post :import }
    collection { post :import_dependents }
    collection { post :import_beneficiaries }
    collection { post :import_correct_mii_recognition_date}
    collection { post :import_members_spouse_as_dependents}
    get "/resignation", to: "members#resignation"
    get "/transfer", to: "members#transfer"
    get "/resignation/edit", to: "members#edit_resignation"
    post "/resignation/:member_resignation_id/update", to: "members#update_resignation", as: :resignation_update
  end

  get "/download_transferred", to: "member_transfer_requests#download_transferred", as: :download_transferred

  # TRANSFER REQUESTS
  resources :member_transfer_requests, only: [:index, :edit, :show, :update]

  namespace :insurance  do
    resources :payment_collections do
      collection { post :upload }
    end
  end

  namespace :income_insurance  do
    resources :payment_collections do
      collection { post :upload }
    end
  end

  resources :feedbacks
  resources :surveys, only: [:index, :show] do
    resources :survey_respondents, except: [:index]
  end

  post "/new_loan_application", to: "loans#new_loan_application", as: :new_loan_application
  post "/new_claim_application", to: "claims#new_claim_application", as: :new_claim_application
  post "/new_clip_claim_application", to: "clip_claims#new_clip_claim_application", as: :new_clip_claim_application

  resources :branches
  resources :centers

  namespace :system_management do
    resources :users
    resources :centers
  end

  namespace :account do
    resources :users
  end

  namespace :accounting do
    get "/dashboard", to: "pages#dashboard"
    resources :loan_payments, only: [:index]
    resources :balance_sheets, only: [:index, :show, :destroy]
    resources :interest_on_share_capital_collections
    resources :patronage_refunds
    get "/patronage_refund/patronage_refund_excel", to: "patronage_refunds#patronage_refund_excel"
    get "/interest_on_share_capital_collection/interest_on_share_capital_excel", to: "interest_on_share_capital_collections#interest_on_share_capital_excel"
    get "/interest_on_share_capital_collection/interest_on_share_capital_pdf", to: "interest_on_share_capital_collections#interest_on_share_capital_pdf", as: :interest_on_share_capital_pdf

    get "/patronage_refund/patronage_refund_collection_pdf", to: "patronage_refunds#patronage_refund_collection_pdf", as: :patronage_refund_collection_pdf
    #get "/interest_on_share_capital_collections/index", to: "interest_on_share_capital_collections#index", as: :interest_on_share_capital_collections
    #get "/patronage_refunds", to: "patronage_refunds#patronage_refund_excel"

    get "/chart_of_accounts", to: "pages#chart_of_accounts", as: :chart_of_accounts
    get "/chart_of_accounts/download", to: "chart_of_accounts#download"
    get "/year_end_closing", to: "pages#year_end_closing"
    get "/income_statement", to: "pages#income_statement"
    get "/balance_sheet", to: "pages#balance_sheet"
    get "/reports/trial_balance", to: "reports#trial_balance", as: :reports_trial_balance
    get "/reports/financial_position", to: "reports#financial_position", as: :reports_financial_position
    get "/reports/statement_of_comprehensive_inc", to: "reports#statement_of_comprehensive_inc", as: :reports_statement_of_comprehensive_inc
  end

  get '/savings_accounts/monthly_interest_tax_generation', to: 'savings_accounts#manual_interest_tax_generation', as: :savings_accounts_manual_interest_tax_generation

  resources :claims do
    get "/claim_validation_pdf", to: "claims#claim_validation_pdf"
    get "/claim_loa_pdf", to: "claims#claim_loa_pdf"
  end

  resources :clip_claims do
    get "/clip_claim_validation_pdf", to: "clip_claims#clip_claim_validation_pdf"
    get "/clip_claim_loa_pdf", to: "clip_claims#clip_claim_loa_pdf"
  end

  resources :loans do
    get "/loan_ledger_pdf", to: "loans#loan_ledger_pdf"
    resources :loan_payments do
      get "approve_payment", to: "loan_payments#approve_payment", as: :approve
      get "reverse_payment", to: "loan_payments#reverse_payment", as: :reverse
    end
    resources :negative_loan_payments, except: [:index, :show]
    get "approve", to: "loans#approve", as: :approve
    get "reverse", to: "loans#reverse", as: :reverse
    get "writeoff", to: "loans#writeoff", as: :writeoff
    get "print_amortization", to: "loans#print_amortization", as: :print_amortization
  end

  resources :loan_insurances do
    collection { post :upload }
    get "approve", to: "loan_insurances#approve", as: :approve
    get "reverse", to: "loan_insurances#reverse", as: :reverse
  end

  resources :reinstatements do
    get "approve", to: "reinstatements#approve", as: :approve
    get "reverse", to: "reinstatements#reverse", as: :reverse
  end

  resources :insurance_account_validations do
    get "approve", to: "insurance_account_validations#approve", as: :approve
    get "reverse", to: "insurance_account_validations#reverse", as: :reverse

    get "/:insurance_account_validation_record_id/withdrawal_pdf", to: "insurance_account_validations#withdrawal_pdf", as: :withdrawal_pdf
    get "/pdf", to: "insurance_account_validations#pdf", as: :pdf
  end

  resources :deceased_and_total_and_permanent_disabilities do
    get "approve", to: "deceased_and_total_and_permanent_disabilities#approve", as: :approve
    get "reverse", to: "deceased_and_total_and_permanent_disabilities#reverse", as: :reverse
  end

  resources :payment_collections do
    get "/download_excel", to: "payment_collections#download_excel", as: :download_excel
    get "/download_wp_list", to: "payment_collections#download_wp_list", as: :download_wp_list
  end

  namespace :membership_payments do
    resources :payment_collections, only: [:index, :new, :show, :destroy, :edit, :update] do
      get "/pdf", to: "payment_collections#pdf"
      resources :payment_collection_records
    end
  end


  namespace :insurance do
    resources :payment_collections do
      get "/pdf", to: "payment_collections#pdf"
    end
  end

  # Member Accounts
  resources :savings_accounts
  resources :insurance_accounts do
    get "/claims_copy_pdf", to: "insurance_accounts#claims_copy_pdf"
    collection { post :import_insurance_accounts }
    collection { post :import_insurance_account_transactions }
    collection { post :import_insured_loans }
  end

  resources :equity_accounts

  # ACCOUNTING ROUTES
  resources :vouchers do
    get "approve", to: "vouchers#approve", as: :approve
    get "/pdf", to: "vouchers#pdf"
    get "/check_pdf", to: "vouchers#check_pdf"
  end

  resources :members do
    get "/change_beneficiaries_pdf", to: "members#change_beneficiaries_pdf"
    get "/blip_form_pdf", to: "members#blip_form_pdf"
    resources :loans, controller: 'members/loans', except: [:destroy] do
      get "/print_check", to: "members/loans#print_check"
      get "/print_voucher", to: "members/loans#print_voucher"
    end
    get "/transactions", to: "members#transactions", as: :transactions
    get "/toggle_active", to: "members#toggle_active", as: :toggle_active

    resources :member_shares, except: [:index] do
      get "/excel", to: "member_shares#excel"
      get "/pdf", to: "member_shares#pdf"
    end

    resources :member_certificates, except: [:index] do
      get "/excel", to: "member_certificates#excel"
      get "/pdf", to: "member_certificates#pdf"
      get "/certificates_for_printing", to: "member_certificates#certificates_for_printing"
    end

    resources :claims, controller: 'members/claims'
    resources :clip_claims, controller: 'members/clip_claims'
  end

  namespace :monitoring do
    resources :daily_reports, only: [:index, :show]
    resources :daily_report_insurance_account_statuses do
      get "/download_excel", to: "daily_report_insurance_account_statuses#download_excel"
    end
  end
  
  namespace :cash_management do
    namespace :time_deposits do
      resources :operation_details do
        collection { get :list_of_time_deposit}
      end
    end
    namespace :operations do
      resources :monthly_interest_and_tax_closing_records, only: [:index, :show, :destroy]
    end

    namespace :insurance_withdrawals do
      resources :payment_collections do
        get "/pdf", to: "payment_collections#pdf"
        collection { post :upload }
      end
    end

    namespace :equity_withdrawals do
      resources :payment_collections do
        get "/pdf", to: "payment_collections#pdf"
        collection { post :upload }
      end
    end

    namespace :deposits do

app/controllers/adjustments/deposits/payment_collections_controller.rb
module Adjustments
  module Deposits
    class PaymentCollectionsController < ApplicationController
      before_action :authenticate_user!
      before_action :load_record, only: [:edit, :update, :destroy, :show]
      before_action :load_types

      def load_record
        @payment_collection = PaymentCollection.find(params[:id])
      end

      def load_types
        if Settings.activate_microloans
          @savings_types    = SavingsType.all
          @equity_types     = EquityType.all
        else
          @savings_types       = []
          @equity_types        = []
        end

        @insurance_types  = InsuranceType.all.order("name ASC")
        @branches         = Branch.all
        @centers          = Center.all
      end
 
      def index
        UserActivity.create!(
          user_id: current_user.id, 
          role: current_user.role, 
          content: "Displayed all payment collections (Deposits)", 
          email: current_user.email, 
          username: current_user.username
        )

        @payment_collections = PaymentCollection.deposit_for_resignation.page params[:page]

        if ["OAS", "BK"].include? current_user.role
          @payment_collections = @payment_collections.where(status: "pending")
        end

        if params[:or_number].present?
          @or_number = params[:or_number]
          @payment_collections = @payment_collections.where("or_number LIKE ?", "#{@or_number}%")
        end

        if params[:start_date].present?
          @start_date = params[:start_date]
          @payment_collections = @payment_collections.where("paid_at >= ?", @start_date)
        end

        if params[:end_date].present?
          @end_date = params[:end_date]
          @payment_collections = @payment_collections.where("paid_at <= ?", @end_date)
        end

        if params[:branch_id].present?
          @branch_id = params[:branch_id]
          @payment_collections = @payment_collections.where(branch_id: params[:branch_id])
        end

        if params[:t_status].present?
          @status = params[:t_status]
          @payment_collections  =  @payment_collections.where(status: @status)
        end

        if params[:center_id].present?
          @center_id  = params[:center_id]
          @payment_collections  = @payment_collections.joins(payment_collection_records: :member).where("members.center_id = ?", @center_id)
        end
      end

      def edit
        UserActivity.create!(
          user_id: current_user.id, 
          role: current_user.role, 
          content: "Edit payment collection (Resignation Deposits)", 
          email: current_user.email, 
          username: current_user.username, 
          record_reference_id: @payment_collection.id
        )

        if @payment_collection.or_number.include?("CHANGE-ME")
          @payment_collection.or_number = ""
        end

        @members  = Member.resigned.where(
                      branch_id: @payment_collection.branch.id
                    ).where.not(
                      id: @payment_collection.payment_collection_records.pluck(:member_id)
                    ).order("last_name ASC")
      end

      def update
        @members  = Member.resigned.where(
                      branch_id: @payment_collection.branch.id
                    ).where.not(
                      id: @payment_collection.payment_collection_records.pluck(:member_id)
                    )

        if @payment_collection.update(payment_collection_params)
          UserActivity.create!(
            user_id: current_user.id, 
            role: current_user.role, 
            content: "Successfully updated payment collection (Resignation Deposits)", 
            email: current_user.email, 
            username: current_user.username, 
            record_reference_id: @payment_collection.id
          )

          flash[:success] = "Successfully saved collection."
          redirect_to adjustments_deposits_payment_collection_path(@payment_collection)
        else
          UserActivity.create!(
            user_id: current_user.id, 
            role: current_user.role, 
            content: "Failed to update payment collection (Resignation Deposits)", 
            email: current_user.email, 
            username: current_user.username, 
            record_reference_id: @payment_collection.id
          )

          flash[:error] = "Error in saving collection. #{@payment_collection.errors.messages}"
          render :edit
        end
      end

      def show
        UserActivity.create!(
          user_id: current_user.id, 
          role: current_user.role, 
          content: "Displaying payment collection (Resignation Deposits)", 
          email: current_user.email, 
          username: current_user.username, 
          record_reference_id: @payment_collection.id
        )

        @members =  Member.resigned.where(
                      branch_id: @payment_collection.branch.id,
                    ).where.not(
                      id: @payment_collection.payment_collection_records.pluck(:member_id)
                    )

        @voucher  = PaymentCollections::ProduceVoucherForDepositPaymentCollection.new(
                      payment_collection: @payment_collection
                    ).execute!
      end

      def pdf
        @payment_collection = PaymentCollection.find(params[:payment_collection_id])
        @insurance_types    = InsuranceType.all.order("name ASC")
        @voucher            = PaymentCollections::ProduceVoucherForDepositPaymentCollection.new(
                                payment_collection: @payment_collection
                              ).execute!

        if Settings.activate_microloans
          @savings_types       = SavingsType.all
          @equity_types        = EquityType.all
        end
      end


      def destroy
        UserActivity.create!(
          user_id: current_user.id, 
          role: current_user.role, 
          content: "Destroying payment collection (Resignation Deposits)", 
          email: current_user.email, 
          username: current_user.username, 
          record_reference_id: @payment_collection.id
        )

        if !@payment_collection.pending?
          UserActivity.create!(
            user_id: current_user.id, 
            role: current_user.role, 
            content: "Failed to destroy payment collection (Resignation Deposits)", 
            email: current_user.email, 
            username: current_user.username, 
            record_reference_id: @payment_collection.id
          )

          flash[:error] = "Cannot destroy non pending record"
          redirect_to adjustments_deposits_payment_collection_path(@payment_collection)
        else
          UserActivity.create!(
            user_id: current_user.id, 
            role: current_user.role, 
            content: "Successfully destroyed payment collection (Resignation Deposits)", 
            email: current_user.email, 
            username: current_user.username, 
            record_reference_id: @payment_collection.id
          )

          @payment_collection.destroy!
          flash[:success] = "Successfully destroyed payment collection."
          redirect_to adjustments_deposits_payment_collections_path
        end
      end

      def payment_collection_params
        params.require(:payment_collection).permit!
      end
    end
  end
end

app/views/cash_management/equity_withdrawals/payment_collections/_actions.html.haml
.ui.grey.segment
  - if payment_collection.pending?
    = link_to edit_cash_management_equity_withdrawals_payment_collection_path(payment_collection), class: "btn btn-app" do
      .fa.fa-pencil
      Edit
    = link_to "#", class: "btn btn-app bg-green", id: "btn-approve" do
      .fa.fa-check
      Approve
    = link_to cash_management_equity_withdrawals_payment_collection_path(payment_collection), class: "btn btn-app bg-red", method: :delete, data: { confirm: "Are you sure?" } do
      .fa.fa-times
      Delete
  - if payment_collection.approved?
    = link_to cash_management_equity_withdrawals_payment_collection_pdf_path(payment_collection), target: "_blank", class: "btn btn-app", id: "btn-print-pdf" do
      .fa.fa-print
      Print PDF

app/views/cash_management/equity_withdrawals/payment_collections/_add_member_actions.html.haml
.well
  .row
    .col-md-8
      = select_tag :member_id, options_for_select(@members.collect{ |o| [o.full_name, o.id] }), class: "select-select2", id: "member-select"
    .col-md-4
      .pull-right
        = link_to "#", class: "btn btn-primary", id: "btn-add-member" do
          .fa.fa-plus
          Add Member

app/views/cash_management/equity_withdrawals/payment_collections/_approve_modal.html.haml
.remodal.modal-approve{ data: { remodal_id: "modal" } }
  %h3
    Approve This Transaction
  .errors
  .success
  .modal-controls
    %hr
    %button#btn-approve-confirmation.btn.btn-primary
      .fa.fa-warning
      Confirm
    %button#btn-cancel-approval.btn.btn-danger
      .fa.fa-times
      Cancel

app/views/cash_management/equity_withdrawals/payment_collections/_danger.html.haml
.ui.red.segment
  %h3
    .fa.fa-warning
    Warning! Danger Zone!
  = link_to "#", class: "btn btn-app bg-red", id: "btn-reverse" do
    .fa.fa-times
    Reverse

app/views/cash_management/equity_withdrawals/payment_collections/_filter.html.haml
%table.table.table-bordered.table-responsive
  %tr
    %th
      %label Branch
      = select_tag :branch_id, options_from_collection_for_select(@branches, :id, :name, Branch.first.try(:id)), class: "form-control select-select2", id: "filter-branch-select", prompt: "-- SELECT --"
    %th
      %label Status
      = select_tag :status, options_for_select(PaymentCollection::STATUSES, @status), id: "filter-status", prompt: "-- ALL --", class: "form-control"
    %th
      %label Start Date
      %input{ type: "text", class: "datepick form-control", placeholder: "Start Date", id: "filter-start-date", value: "#{@start_date}" }
    %th
      %label End Date
      %input{ type: "text", class: "datepick form-control", placeholder: "End Date", id: "filter-end-date", value: "#{@end_date}" }
    %th
      %label Actions
      %br
      %button#btn-filter.btn.btn-primary
        .fa.fa-search
        Search

app/views/cash_management/equity_withdrawals/payment_collections/_form.html.haml
- if @errors
  .bs-callout.bs-callout-error
    %h4 Errors
    %ul
      - @errors.each do |e|
        %li
          #{e}

= render partial: "add_member_actions", locals: { payment_collection: @payment_collection }
= simple_form_for [:cash_management, :equity_withdrawals, payment_collection], defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } }, html: { novalidate: true } do |f|
  %table.table.table-bordered.table-responsive.transaction-table
    %thead
      %tr
        %th{width: "20%"} Member
        - @insurance_types.where(code: "LIF").each do |insurance_type|
          %th #{insurance_type.code} - Equity Value
        %th Amt
        %th Actions
    %tbody
      = f.simple_fields_for :payment_collection_records, f.object.payment_collection_records.sort_by{ |o| o.member.last_name } do |ff|
        %tr
          %td #{link_to ff.object.member.full_name, member_path(ff.object.member), target: "_blank"}
          - @insurance_types.where(code: "LIF").each do |insurance_type|
            %td
              = ff.simple_fields_for :collection_transactions do |fff|
                - if fff.object.account_type == "INSURANCE" and fff.object.account_type_code == insurance_type.code
                  = fff.input :amount, label: false, input_html: { class: "form-control numeric insurance-withdrawal cp-amount", data: { member_id: "#{ff.object.member.id}", account_code: "#{insurance_type.code}" } }
          %td
            %input{type: "text", class: "form-control numeric total-member-amount", disabled: true, value: 0.00, data: { member_id: "#{ff.object.member.id}" }}
          %td
            = link_to "#", class: "btn btn-danger btn-delete", data: { payment_collection_record_id: ff.object.id } do
              .fa.fa-times
              Delete
      %thead
        %tr
          %th{width: "20%"} Total
          - @insurance_types.where(code: "LIF").each do |insurance_type|
            %th
              %input{type: "text", class: "form-control numeric total-insurance", disabled: true, value: 0.00, data: { insurance_type_code: "#{insurance_type.code}"}}
          %th
            %input{type: "text", class: "form-control numeric grand-total", disabled: true, value: 0.00}
          %th
  .well
    %label
      For Adjustment
    = f.input :for_adjustment, input_html: { class: "switch" }, label: false
    = f.input :particular
  %hr
  .form-actions
    = button_tag(type: "submit", class: "btn btn-primary") do
      .fa.fa-check
      Save
    = link_to cash_management_equity_withdrawals_payment_collection_path(@payment_collection), class: "btn btn-danger" do
      .fa.fa-times
      Cancel

#parameters{data: {payment_collection_id: @payment_collection.id, insurance_types: @insurance_types.where(code: "LIF").pluck(:code) }}
= render partial: "shared/loading_modal"
= javascript_include_tag "CashManagementEquityWithdrawalsPaymentCollectionForm"

:javascript
  $(document).ready(function() {
    CashManagementEquityWithdrawalsCollectionForm.init();
  });

app/views/cash_management/equity_withdrawals/payment_collections/_generate_billing_modal.html.haml
.remodal.modal-generate-withdrawal-payment-collection{ data: { remodal_id: "modal" } }
  %h3
    Generate New Withdrawal Transaction
  .errors
  .success
  .controls
    .row
      .col-md-6
        %label
          Branch
        = select_tag :branch_id, options_for_select(@branches.collect{ |o| [o.name, o.id] }), class: "select-select2", id: "modal-branch-select"
      .col-md-6
        %label
          Date of Payment
        %input{ type: "text", id: "date-of-payment", class: "form-control datepick", value: Time.now.strftime("%Y-%m-%d") }

    %hr
    %button#btn-generate-billing.btn.btn-success
      .fa.fa-warning
      Confirm
    %button#btn-cancel-generate-billing.btn.btn-danger
      .fa.fa-times
      Cancel

app/views/cash_management/equity_withdrawals/payment_collections/_list.html.haml
.table-responsive.no-padding
  %table.payments.table-bordered.table{:style => "margin-top: 10px;"}
    %tbody
      %tr
        %th Date
        %th Branch
        %th.accounting-curr Total Amount
        %th Status
      - @payment_collections.each do |pc|
        %tr.clickable{ data: { transaction_id: "#{pc.id}" } }
          %td #{pc.paid_at.strftime("%B %d, %Y")}
          %td #{pc.branch}
          %td.curr #{number_to_currency(pc.total_amount, unit: "P")}
          %td #{pc.status}

app/views/cash_management/equity_withdrawals/payment_collections/_payment_records.html.haml
%table.table.table-bordered.table-responsive.transaction-table.payments
  %thead
    %tr
      %th{width: "2%"}
      %th{width: "20%"} Member
      - @insurance_types.where(code: "LIF").each do |insurance_type|
        %th #{insurance_type.code} - Equity Value
      %th Amt Rec
  %tbody
    - payment_collection.payment_collection_records.joins(:member).order("members.last_name ASC").each_with_index do |payment_collection_record, i|
      %tr
        %td #{i + 1}
        %td
          = link_to "#{payment_collection_record.member.full_name}", member_path(payment_collection_record.member), target: "_blank"
        - @insurance_types.where(code: "LIF").each do |insurance_type|
          %td
            - payment_collection_record.collection_transactions.where(account_type: "INSURANCE").each do |collection_transaction|
              - if collection_transaction.account_type == "INSURANCE" and collection_transaction.account_type_code == insurance_type.code
                #{number_to_currency(collection_transaction.amount, unit: "P")}
        %td
          #{number_to_currency(payment_collection_record.total_cp_amount, unit: "P")}
  %thead
    %tr
      %th
      %th{width: "20%"} Total
      - @insurance_types.where(code: "LIF").each do |insurance_type|
        %th #{number_to_currency(CollectionTransaction.where(payment_collection_record_id: payment_collection.payment_collection_records.pluck(:id), account_type: "INSURANCE", account_type_code: insurance_type.code).sum(:amount), unit: "P")}
      %th #{number_to_currency(payment_collection.total_amount, unit: "P")}

app/views/cash_management/equity_withdrawals/payment_collections/_reverse_modal.html.haml
.remodal.modal-reverse{ data: { remodal_id: "modal" } }
  %h3
    Reverse This Transaction
  .errors
  .success
  .modal-controls
    %hr
    %button#btn-reverse-confirmation.ui.primary.button
      .fa.fa-warning
      Confirm
    %button#btn-cancel-reverse.ui.default.button
      .fa.fa-times
      Cancel

app/views/cash_management/equity_withdrawals/payment_collections/edit.html.haml
%section.content-header
  %h1
    Equity Withdrawal Form
    %small
      #{@payment_collection.paid_at}
  %ol.breadcrumb
    %li
      #{link_to "Payments", cash_management_equity_withdrawals_payment_collections_path}
    %li
      #{link_to "Show", cash_management_equity_withdrawals_payment_collection_path(@payment_collection)}
    %li
      Edit
%section.content
  = render partial: "form", locals: { payment_collection: @payment_collection }

app/views/cash_management/equity_withdrawals/payment_collections/index.html.haml
%section.content-header
  %h1 Equity Withdrawals
  %ol.breadcrumb
    %li{:style => "margin-top: -10px;"}
      = link_to "#", id: "btn-new-withdrawal", class: 'btn btn-primary bg-blue', style: 'color: #fff;' do
        .fa.fa-plus
        Add Withdrawal Transaction
%section.content
  .errors
  = render partial: "filter"
  - if @payment_collections.size == 0
    %p
      No transactions found
  - else
    = render partial: "list", locals: { payment_collections: @payment_collections }
    .row
      .col-md-12
        .pull-right
          = paginate @payment_collections    

= render partial: "generate_billing_modal"
= render partial: "shared/errors_template"
= render partial: "shared/success_template"
= render partial: "shared/loading_modal"
= javascript_include_tag "CashManagementEquityWithdrawalsPaymentCollections"

:javascript
  $(document).ready(function() {
    CashManagementEquityWithdrawalsPaymentCollections.init();
  });

app/views/cash_management/equity_withdrawals/payment_collections/show.html.haml
#parameters{ data: { payment_collection_id: @payment_collection.id } }

%section.content-header
  %h1
    Equity Withdrawal
    %small
      #{@payment_collection.paid_at.strftime("%b %d, %Y")}
  %ol.breadcrumb
    %li
      #{link_to "Withdrawals", cash_management_equity_withdrawals_payment_collections_path}
    %li
      Show
%section.content
  .well
    = render partial: "actions", locals: { payment_collection: @payment_collection }
  .box
    .box-body
      - if @payment_collection.for_adjustment?
        .bs-callout.bs-callout-info
          %h3
            .fa.fa-warning
              This transaction is for adjustment
      = render partial: "shared/errors"
      = render partial: "payment_records", locals: { payment_collection: @payment_collection }
  .well
    %p
      #{@payment_collection.particular}

= render partial: "approve_modal"
= render partial: "reverse_modal"
= render partial: "shared/errors_template"
= render partial: "shared/success_template"
= render partial: "shared/errors"
= javascript_include_tag "CashManagementEquityWithdrawalsPaymentCollection"
:javascript
  $(document).ready(function() {
    CashManagementEquityWithdrawalsPaymentCollection.init();
  });